---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'


platforms:
  - name: ubuntu-18.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    attributes:
      docker_install:
        docker:
          version: '17.09.0'
          members: [ 'vagrant', 'user1', 'user2' ]
          distribution: "ubuntu-bionic"

  - name: ubuntu-16.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    attributes:
      docker_install:
        docker:
          version: '17.09.0'
          members: [ 'vagrant', 'user1', 'user2' ]
          distribution: "ubuntu-xenial"

  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    attributes:
      docker_install:
        docker:
          version: '17.09.0'
          members: [ 'vagrant', 'user1', 'user2' ]
          distribution: "ubuntu-trusty"

suites:
  - name: default
    run_list:
      - recipe[localsetup]
      - recipe[docker-install::docker-install]
    attributes:
      docker_install:
        docker:
          images:
            - name: 'hello-world'
              tag: 'latest'
            - name: 'python'
              tag: '3.6.1'
            - name: 'python'
              tag: '2.7.13'
