---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  chef_omnibus_install_options: ' -d /tmp/vagrant-cache/vagrant_omnibus'


platforms:
  - name: ubuntu-16.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    attributes:
      docker_install:
        docker:
          #version: '1.10.3'
          version: '1.12.3'
          distribution: "ubuntu-xenial"

  - name: ubuntu-14.04
    driver:
      vagrantfile_erb: Vagrantfile.erb
      synced_folders:
        - ['./result', '/tmp/result']
    attributes:
      docker_install:
        docker:
          #version: '1.10.3'
          version: '1.12.3'
          distribution: "ubuntu-trusty"

suites:
  - name: default
    run_list:
      - recipe[docker-install::docker-install]
